export const items = [
  {
    id: 1,
    category: "mobiles",
    title: "Apple iPhone 14",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Apple iPhone 14 (128 GB) - Blue",
    price: "89999",
  },
  {
    id: 5,
    category: "laptops",
    title: "Xiaomi [Smartchoice] Notebookpro",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3EzeQaC",
    description: "Xiaomi [Smartchoice] Notebookpro ",
    price: "49999",
  },
  {
    id: 7,
    category: "tablets",
    title: "Xiaomi Pad 6",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3ZeNRdY",
    description: "Xiaomi Pad 6| Qualcomm Snapdragon 870| ",
    price: "29999",
  },
  {
    id: 2,
    category: "mobiles",
    title: "Apple iPhone 11",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/44MiYi6",
    description: "Apple iPhone 11 (64GB) - White",
    price: "79999",
  },
  {
    id: 6,
    category: "tablets",
    title: "Lenovo Tab P12 Pro AMOLED",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3RabsdH",
    description:
      "Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3",
    price: "19999",
  },
  {
    id: 3,
    category: "mobiles",
    title: "Apple iPhone 13",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r6XJtv",
    description: "Apple iPhone 13 (128GB) - Blue",
    price: "69999",
  },
  {
    id: 4,
    category: "laptops",
    title: "Lenovo IdeaPad Slim 5 ",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/44JsK4r",
    description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
    price: "29999",
  },
  {
    id: 8,
    category: "laptops",
    title: "Apple MacBook Air Laptop",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r9rvhm",
    description:
      "Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ",
    price: "89999",
  },
  {
    id: 9,
    category: "tablets",
    title: "Samsung Galaxy Tab A8",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3Pdsh4F",
    description:
      "Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)",
    price: "49999",
  },
];

//CLOUTH DATA......................................

export const clouth = [
  {
    id: 1,
    category: "jeans",
    title: "Levi's Men's 511 Slim Fit Jeans",
    imgSrc: "https://m.media-amazon.com/images/I/81gWTENwJUL._SY879_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Levi's Men's 511 Slim Fit Jeans - Dark Blue",
    price: "3999",
  },
  {
    id: 2,
    category: "shirts",
    title: "Van Heusen Men's Regular Fit Shirt",
    imgSrc: "https://m.media-amazon.com/images/I/71B-w9JNvgL._SY879_.jpg",
    amazonLink: "https://amzn.to/3EzeQaC",
    description: "Van Heusen Men's Regular Fit Casual Shirt - Light Blue",
    price: "1799",
  },
  {
    id: 3,
    category: "t-shirts",
    title: "Puma Men's Cotton T-Shirt",
    imgSrc: "https://m.media-amazon.com/images/I/51dAPPq6qnL._SX679_.jpg",
    amazonLink: "https://amzn.to/3ZeNRdY",
    description: "Puma Men's Cotton T-Shirt - Black",
    price: "999",
  },
  {
    id: 4,
    category: "jeans",
    title: "Lee Men's Regular Fit Jeans",
    imgSrc: "https://m.media-amazon.com/images/I/719E527BwbL._SX679_.jpg",
    amazonLink: "https://amzn.to/44MiYi6",
    description: "Lee Men's Regular Fit Jeans - Light Blue",
    price: "2999",
  },
  {
    id: 5,
    category: "shirts",
    title: "Amazon Brand - Symbol Men's Shirt",
    imgSrc: "https://m.media-amazon.com/images/I/61gDZASPaOL._SY879_.jpg",
    amazonLink: "https://amzn.to/3RabsdH",
    description: "Amazon Brand - Symbol Men's Casual Shirt - White",
    price: "1299",
  },
  {
    id: 6,
    category: "t-shirts",
    title: "Nike Men's Graphic T-Shirt",
    imgSrc: "https://m.media-amazon.com/images/I/61cybSns+eL._SY879_.jpg",
    amazonLink: "https://amzn.to/3r6XJtv",
    description: "Nike Men's Graphic T-Shirt - Grey",
    price: "1199",
  },
  {
    id: 7,
    category: "jeans",
    title: "Wrangler Men's Regular Fit Jean",
    imgSrc: "https://m.media-amazon.com/images/I/71aJmzVWV+L._SX679_.jpg",
    amazonLink: "https://amzn.to/44JsK4r",
    description: "Wrangler Men's Regular Fit Jeans - Black",
    price: "3299",
  },
  {
    id: 8,
    category: "shirts",
    title: "H&M Men's Slim Fit Shirt",
    imgSrc: "https://m.media-amazon.com/images/I/511mroWTy+L._SY879_.jpg",
    amazonLink: "https://amzn.to/3r9rvhm",
    description: "H&M Men's Slim Fit Casual Shirt - Green",
    price: "1499",  
  },
  {
    id: 9,
    category: "t-shirts",
    title: "Adidas Men's Solid T-Shirt",
    imgSrc: "https://m.media-amazon.com/images/I/41Ob92BPE0L._SX679_.jpg",
    amazonLink: "https://amzn.to/3Pdsh4F",
    description: "Adidas Men's Solid T-Shirt - Blue",
    price: "1099",
  },
];

export const jewelry = [
  {
    id: 1,
    category: "necklaces",
    title: "Gold Plated Necklace",
    imgSrc: "https://m.media-amazon.com/images/I/71iXDEOuGeL._SY695_.jpg",
    amazonLink: "https://amzn.to/3sdfgfd",
    description: "Elegant gold plated necklace with intricate design.",
    price: "1999",
  },
  {
    id: 2,
    category: "earrings",
    title: "Silver Hoop Earrings",
    imgSrc: "https://m.media-amazon.com/images/I/31QO51qxOpL.jpg",
    amazonLink: "https://amzn.to/3r6WQ1s",
    description: "Stylish silver hoop earrings for everyday wear.",
    price: "999",
  },
  {
    id: 3,
    category: "rings",
    title: "Diamond Ring",
    imgSrc: "https://m.media-amazon.com/images/I/61mparIWdqL._SY695_.jpg",
    amazonLink: "https://amzn.to/3P1gH54",
    description: "Beautiful diamond ring perfect for special occasions.",
    price: "4999",
  },
  {
    id: 4,
    category: "necklaces",
    title: "Pearl Necklace",
    imgSrc: "https://m.media-amazon.com/images/I/51VWUYXJ94L._SY695_.jpg",
    amazonLink: "https://amzn.to/3Pf3GZg",
    description: "Classic pearl necklace that adds elegance to any outfit.",
    price: "2999",
  },
  {
    id: 5,
    category: "earrings",
    title: "Stud Earrings",
    imgSrc: "https://m.media-amazon.com/images/I/61reu8oupFL._SY695_.jpg",
    amazonLink: "https://amzn.to/3Rcb2ji",
    description: "Simple and elegant stud earrings for daily wear.",
    price: "899",
  },
  {
    id: 6,
    category: "rings",
    title: "Gold Wedding Ring",
    imgSrc: "https://m.media-amazon.com/images/I/61N7rDkuNnL._SY695_.jpg",
    amazonLink: "https://amzn.to/3y7fhgf",
    description: "Classic gold wedding ring that symbolizes love.",
    price: "5999",
  },
  {
    id: 7,
    category: "necklaces",
    title: "Choker Necklace",
    imgSrc: "https://m.media-amazon.com/images/I/61jjIaG9H-L._SY695_.jpg",
    amazonLink: "https://amzn.to/3sdfgfd",
    description: "Trendy choker necklace that complements any outfit.",
    price: "1499",
  },
  {
    id: 8,
    category: "earrings",
    title: "Drop Earrings",
    imgSrc: "https://m.media-amazon.com/images/I/61pYO5D2R7L._SY695_.jpg",
    amazonLink: "https://amzn.to/3r8bcgv",
    description: "Elegant drop earrings that make a statement.",
    price: "1799",
  },
  {
    id: 9,
    category: "rings",
    title: "Silver Promise Ring",
    imgSrc: "https://m.media-amazon.com/images/I/719DUKaMV5L._SY695_.jpg",
    amazonLink: "https://amzn.to/3r7bgfg",
    description: "Beautiful silver promise ring for special moments.",
    price: "2499",
  },
];
